import './globals.css'
import Navigation from '../components/navigation'
import Footer from '@/components/auth/footer'
import { AuthProvider } from '@/contexts'


export const metadata = {
  title: 'Tienda de prueba',
  description: 'Generated by Manuel Pérez',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          <Navigation />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
